### PR TITLE
Escape all request values

### PR DESCRIPTION
**Pull request by diastremskii**
Some symbols should be escaped or Last.fm won't handle them correctly.
For example:
```
import curryfm from 'curryfm';
import readjson from 'read-json-sync';

const { api_key: API_KEY } = readjson("./config.json");

const client = curryfm(API_KEY);

const artistClient = client('artist');
artistClient ('getInfo', {
    artist: 'Ill Niño',
    format: 'json'
  }).then(res => {
    if (res.error) {
      console.log(res.error)
    };
});
```
For this example Last.fm responds with 'The artist you supplied could not be found', however this artist does exist.

### CODE REVIEW

**Comment by f0rr0** [comment]
@TheBeastOfCaerbannog can you add the dependency to package.json?

**Comment by diastremskii** [comment]
@f0rr0 I guess there is no need for adding it as a dependency, it's not an NPM module, it's a part of standard Node.js modules: https://nodejs.org/dist/latest-v6.x/docs/api/querystring.html

**Comment by f0rr0** [comment]
@TheBeastOfCaerbannog damn! never knew that, cool merging this

**Comment by diastremskii** [comment]
Can you also update curryfm version in NPM please? :)
I forgot to bump version in PR

**Comment by f0rr0** [comment]
@TheBeastOfCaerbannog done

**Comment by diastremskii** [comment]
@f0rr0 Thanks :)

**Pull request merged**
